import { sql } from "drizzle-orm";
import {
  boolean,
  check,
  date,
  foreignKey,
  index,
  integer,
  numeric,
  pgTable,
  text,
  unique,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";

import { addresses, companies, people } from "./core.js";
import {
  createdAtColumn,
  jsonObjectColumn,
  nullableJsonObjectColumn,
  sourceMetadataColumns,
  updatedAtColumn,
} from "./shared.js";

export const parcels = pgTable(
  "parcels",
  {
    parcelId: uuid("parcel_id").primaryKey().defaultRandom(),
    requestIdentifier: text("request_identifier"),
    parcelIdentifier: text("parcel_identifier").notNull(),
    countyName: text("county_name"),
    stateCode: text("state_code"),
    jurisdictionKey: text("jurisdiction_key"),
    sourceHttpRequest: nullableJsonObjectColumn("source_http_request"),
    sourcePayload: jsonObjectColumn("source_payload"),
    ...sourceMetadataColumns(),
    createdAt: createdAtColumn(),
    updatedAt: updatedAtColumn(),
  },
  (table) => [
    uniqueIndex("parcels_source_record_idx").on(table.sourceSystem, table.sourceRecordKey),
    unique("parcels_jurisdiction_key_parcel_identifier_unique").on(
      table.jurisdictionKey,
      table.parcelIdentifier,
    ),
    index("parcels_identifier_idx").on(table.parcelIdentifier),
  ],
);

export const properties = pgTable(
  "properties",
  {
    propertyId: uuid("property_id").primaryKey().defaultRandom(),
    parcelId: uuid("parcel_id").references(() => parcels.parcelId, {
      onDelete: "set null",
    }),
    addressId: uuid("address_id").references(() => addresses.addressId, {
      onDelete: "set null",
    }),
    requestIdentifier: text("request_identifier"),
    parcelIdentifier: text("parcel_identifier").notNull(),
    propertyType: text("property_type"),
    propertyUsageType: text("property_usage_type"),
    structureForm: text("structure_form"),
    buildStatus: text("build_status"),
    ownershipEstateType: text("ownership_estate_type"),
    propertyLegalDescriptionText: text("property_legal_description_text"),
    propertyStructureBuiltYear: integer("property_structure_built_year"),
    propertyEffectiveBuiltYear: integer("property_effective_built_year"),
    historicDesignation: boolean("historic_designation"),
    livableFloorArea: text("livable_floor_area"),
    areaUnderAir: text("area_under_air"),
    totalArea: text("total_area"),
    numberOfUnits: integer("number_of_units"),
    numberOfUnitsType: text("number_of_units_type"),
    subdivision: text("subdivision"),
    zoning: text("zoning"),
    sourceHttpRequest: nullableJsonObjectColumn("source_http_request"),
    sourcePayload: jsonObjectColumn("source_payload"),
    ...sourceMetadataColumns(),
    createdAt: createdAtColumn(),
    updatedAt: updatedAtColumn(),
  },
  (table) => [
    uniqueIndex("properties_source_record_idx").on(table.sourceSystem, table.sourceRecordKey),
    index("properties_parcel_identifier_idx").on(table.parcelIdentifier),
    index("properties_parcel_idx").on(table.parcelId),
    index("properties_address_idx").on(table.addressId),
  ],
);

export const ownerships = pgTable(
  "ownerships",
  {
    ownershipId: uuid("ownership_id").primaryKey().defaultRandom(),
    propertyId: uuid("property_id").references(() => properties.propertyId, {
      onDelete: "cascade",
    }),
    ownerPersonId: uuid("owner_person_id").references(() => people.personId, {
      onDelete: "set null",
    }),
    ownerCompanyId: uuid("owner_company_id").references(() => companies.companyId, {
      onDelete: "set null",
    }),
    mailingAddressId: uuid("mailing_address_id").references(() => addresses.addressId, {
      onDelete: "set null",
    }),
    ownershipIdentifier: text("ownership_identifier"),
    ownedBy: text("owned_by"),
    propertyOwnershipStructure: text("property_ownership_structure"),
    propertyOwnershipStructureOtherDescription: text(
      "property_ownership_structure_other_description",
    ),
    trustInformation: text("trust_information"),
    ownershipPercentage: numeric("ownership_percentage", { precision: 7, scale: 4 }),
    ownerOccupiedIndicator: boolean("owner_occupied_indicator"),
    dateAcquired: date("date_acquired"),
    dateSold: date("date_sold"),
    sourcePayload: jsonObjectColumn("source_payload"),
    ...sourceMetadataColumns(),
    createdAt: createdAtColumn(),
    updatedAt: updatedAtColumn(),
  },
  (table) => [
    uniqueIndex("ownerships_source_record_idx").on(table.sourceSystem, table.sourceRecordKey),
    index("ownerships_property_idx").on(table.propertyId),
    index("ownerships_owner_person_idx").on(table.ownerPersonId),
    index("ownerships_owner_company_idx").on(table.ownerCompanyId),
    index("ownerships_mailing_address_idx").on(table.mailingAddressId),
    check(
      "ownerships_percentage_check",
      sql`${table.ownershipPercentage} IS NULL OR (${table.ownershipPercentage} >= 0 AND ${table.ownershipPercentage} <= 100)`,
    ),
  ],
);

export const taxes = pgTable(
  "taxes",
  {
    taxId: uuid("tax_id").primaryKey().defaultRandom(),
    propertyId: uuid("property_id").references(() => properties.propertyId, {
      onDelete: "cascade",
    }),
    requestIdentifier: text("request_identifier"),
    taxYear: integer("tax_year"),
    propertyAssessedValueAmount: numeric("property_assessed_value_amount", {
      precision: 18,
      scale: 2,
    }),
    propertyMarketValueAmount: numeric("property_market_value_amount", {
      precision: 18,
      scale: 2,
    }),
    propertyBuildingAmount: numeric("property_building_amount", {
      precision: 18,
      scale: 2,
    }),
    propertyLandAmount: numeric("property_land_amount", { precision: 18, scale: 2 }),
    propertyExemptionAmount: numeric("property_exemption_amount", {
      precision: 18,
      scale: 2,
    }),
    propertyTaxableValueAmount: numeric("property_taxable_value_amount", {
      precision: 18,
      scale: 2,
    }),
    cityTaxableValueAmount: numeric("city_taxable_value_amount", {
      precision: 18,
      scale: 2,
    }),
    countyTaxableValueAmount: numeric("county_taxable_value_amount", {
      precision: 18,
      scale: 2,
    }),
    collegeTaxableValueAmount: numeric("college_taxable_value_amount", {
      precision: 18,
      scale: 2,
    }),
    hospitalTaxableValueAmount: numeric("hospital_taxable_value_amount", {
      precision: 18,
      scale: 2,
    }),
    schoolTaxableValueAmount: numeric("school_taxable_value_amount", {
      precision: 18,
      scale: 2,
    }),
    specialDistrictTaxableValueAmount: numeric("special_district_taxable_value_amount", {
      precision: 18,
      scale: 2,
    }),
    agriculturalValuationAmount: numeric("agricultural_valuation_amount", {
      precision: 18,
      scale: 2,
    }),
    homesteadCapLossAmount: numeric("homestead_cap_loss_amount", {
      precision: 18,
      scale: 2,
    }),
    buildingReplacementCostAmount: numeric("building_replacement_cost_amount", {
      precision: 18,
      scale: 2,
    }),
    buildingDepreciatedValueAmount: numeric("building_depreciated_value_amount", {
      precision: 18,
      scale: 2,
    }),
    millageRate: numeric("millage_rate", { precision: 12, scale: 6 }),
    monthlyTaxAmount: numeric("monthly_tax_amount", { precision: 18, scale: 2 }),
    yearlyTaxAmount: numeric("yearly_tax_amount", { precision: 18, scale: 2 }),
    periodStartDate: date("period_start_date"),
    periodEndDate: date("period_end_date"),
    firstYearOnTaxRoll: integer("first_year_on_tax_roll"),
    firstYearBuildingOnTaxRoll: integer("first_year_building_on_tax_roll"),
    sourceHttpRequest: nullableJsonObjectColumn("source_http_request"),
    sourcePayload: jsonObjectColumn("source_payload"),
    ...sourceMetadataColumns(),
    createdAt: createdAtColumn(),
    updatedAt: updatedAtColumn(),
  },
  (table) => [
    uniqueIndex("taxes_source_record_idx").on(table.sourceSystem, table.sourceRecordKey),
    unique("taxes_property_id_tax_year_unique").on(
      table.propertyId,
      table.taxYear,
    ),
    index("taxes_tax_year_idx").on(table.taxYear),
  ],
);

export const salesHistories = pgTable(
  "sales_histories",
  {
    salesHistoryId: uuid("sales_history_id").primaryKey().defaultRandom(),
    propertyId: uuid("property_id").references(() => properties.propertyId, {
      onDelete: "cascade",
    }),
    requestIdentifier: text("request_identifier"),
    ownershipTransferDate: date("ownership_transfer_date"),
    purchasePriceAmount: numeric("purchase_price_amount", { precision: 18, scale: 2 }),
    saleType: text("sale_type"),
    deedBook: text("deed_book"),
    deedPage: text("deed_page"),
    instrumentNumber: text("instrument_number"),
    sourceHttpRequest: nullableJsonObjectColumn("source_http_request"),
    sourcePayload: jsonObjectColumn("source_payload"),
    ...sourceMetadataColumns(),
    createdAt: createdAtColumn(),
    updatedAt: updatedAtColumn(),
  },
  (table) => [
    uniqueIndex("sales_histories_source_record_idx").on(table.sourceSystem, table.sourceRecordKey),
    index("sales_histories_property_date_idx").on(
      table.propertyId,
      table.ownershipTransferDate,
    ),
  ],
);

export const propertyValuations = pgTable(
  "property_valuations",
  {
    propertyValuationId: uuid("property_valuation_id").primaryKey().defaultRandom(),
    propertyId: uuid("property_id").references(() => properties.propertyId, {
      onDelete: "cascade",
    }),
    valuationDate: date("valuation_date"),
    valuationMethodType: text("valuation_method_type"),
    confidenceScore: integer("confidence_score"),
    currentAvmValue: numeric("current_avm_value", { precision: 18, scale: 2 }),
    highValue: numeric("high_value", { precision: 18, scale: 2 }),
    lowValue: numeric("low_value", { precision: 18, scale: 2 }),
    standardDeviation: numeric("standard_deviation", { precision: 18, scale: 6 }),
    areaMinPropertyPricePsf: numeric("area_min_property_price_psf", {
      precision: 18,
      scale: 6,
    }),
    areaMaxPropertyPricePsf: numeric("area_max_property_price_psf", {
      precision: 18,
      scale: 6,
    }),
    sourcePayload: jsonObjectColumn("source_payload"),
    ...sourceMetadataColumns(),
    createdAt: createdAtColumn(),
    updatedAt: updatedAtColumn(),
  },
  (table) => [
    uniqueIndex("property_valuations_source_record_idx").on(table.sourceSystem, table.sourceRecordKey),
    index("property_valuations_property_date_idx").on(
      table.propertyId,
      table.valuationDate,
    ),
    check(
      "property_valuations_confidence_score_check",
      sql`${table.confidenceScore} IS NULL OR (${table.confidenceScore} >= 0 AND ${table.confidenceScore} <= 100)`,
    ),
  ],
);

export const factSheets = pgTable(
  "fact_sheets",
  {
    factSheetId: uuid("fact_sheet_id").primaryKey().defaultRandom(),
    propertyId: uuid("property_id").references(() => properties.propertyId, {
      onDelete: "set null",
    }),
    requestIdentifier: text("request_identifier"),
    ipfsUrl: text("ipfs_url"),
    fullGenerationCommand: text("full_generation_command"),
    sourcePayload: jsonObjectColumn("source_payload"),
    ...sourceMetadataColumns(),
    createdAt: createdAtColumn(),
    updatedAt: updatedAtColumn(),
  },
  (table) => [
    uniqueIndex("fact_sheets_source_record_idx").on(table.sourceSystem, table.sourceRecordKey),
    index("fact_sheets_property_idx").on(table.propertyId),
  ],
);

export const geometries = pgTable(
  "geometries",
  {
    geometryId: uuid("geometry_id").primaryKey().defaultRandom(),
    propertyId: uuid("property_id").references(() => properties.propertyId, {
      onDelete: "set null",
    }),
    requestIdentifier: text("request_identifier"),
    latitude: numeric("latitude", { precision: 10, scale: 7 }),
    longitude: numeric("longitude", { precision: 10, scale: 7 }),
    sourceHttpRequest: nullableJsonObjectColumn("source_http_request"),
    sourcePayload: jsonObjectColumn("source_payload"),
    ...sourceMetadataColumns(),
    createdAt: createdAtColumn(),
    updatedAt: updatedAtColumn(),
  },
  (table) => [
    uniqueIndex("geometries_source_record_idx").on(table.sourceSystem, table.sourceRecordKey),
    index("geometries_property_idx").on(table.propertyId),
  ],
);

export const deeds = pgTable(
  "deeds",
  {
    deedId: uuid("deed_id").primaryKey().defaultRandom(),
    propertyId: uuid("property_id").references(() => properties.propertyId, {
      onDelete: "set null",
    }),
    requestIdentifier: text("request_identifier"),
    deedType: text("deed_type"),
    book: text("book"),
    page: text("page"),
    instrumentNumber: text("instrument_number"),
    sourceHttpRequest: nullableJsonObjectColumn("source_http_request"),
    sourcePayload: jsonObjectColumn("source_payload"),
    ...sourceMetadataColumns(),
    createdAt: createdAtColumn(),
    updatedAt: updatedAtColumn(),
  },
  (table) => [
    uniqueIndex("deeds_source_record_idx").on(table.sourceSystem, table.sourceRecordKey),
    index("deeds_property_idx").on(table.propertyId),
    index("deeds_book_page_idx").on(table.book, table.page),
  ],
);

export const files = pgTable(
  "files",
  {
    fileId: uuid("file_id").primaryKey().defaultRandom(),
    propertyId: uuid("property_id").references(() => properties.propertyId, {
      onDelete: "set null",
    }),
    deedId: uuid("deed_id").references(() => deeds.deedId, {
      onDelete: "set null",
    }),
    requestIdentifier: text("request_identifier"),
    documentType: text("document_type"),
    fileFormat: text("file_format"),
    ipfsUrl: text("ipfs_url"),
    name: text("name"),
    originalUrl: text("original_url"),
    sourceHttpRequest: nullableJsonObjectColumn("source_http_request"),
    sourcePayload: jsonObjectColumn("source_payload"),
    ...sourceMetadataColumns(),
    createdAt: createdAtColumn(),
    updatedAt: updatedAtColumn(),
  },
  (table) => [
    uniqueIndex("files_source_record_idx").on(table.sourceSystem, table.sourceRecordKey),
    index("files_property_idx").on(table.propertyId),
    index("files_deed_idx").on(table.deedId),
    index("files_original_url_idx").on(table.originalUrl),
  ],
);

export const structures = pgTable(
  "structures",
  {
    structureId: uuid("structure_id").primaryKey().defaultRandom(),
    propertyId: uuid("property_id").references(() => properties.propertyId, {
      onDelete: "set null",
    }),
    requestIdentifier: text("request_identifier"),
    architecturalStyleType: text("architectural_style_type"),
    attachmentType: text("attachment_type"),
    exteriorWallMaterialPrimary: text("exterior_wall_material_primary"),
    exteriorWallMaterialSecondary: text("exterior_wall_material_secondary"),
    exteriorWallCondition: text("exterior_wall_condition"),
    exteriorWallConditionPrimary: text("exterior_wall_condition_primary"),
    exteriorWallConditionSecondary: text("exterior_wall_condition_secondary"),
    exteriorWallInsulationType: text("exterior_wall_insulation_type"),
    exteriorWallInsulationTypePrimary: text("exterior_wall_insulation_type_primary"),
    exteriorWallInsulationTypeSecondary: text("exterior_wall_insulation_type_secondary"),
    roofCoveringMaterial: text("roof_covering_material"),
    roofMaterialType: text("roof_material_type"),
    roofDesignType: text("roof_design_type"),
    roofCondition: text("roof_condition"),
    roofAgeYears: integer("roof_age_years"),
    roofDate: text("roof_date"),
    roofUnderlaymentType: text("roof_underlayment_type"),
    roofStructureMaterial: text("roof_structure_material"),
    foundationType: text("foundation_type"),
    foundationMaterial: text("foundation_material"),
    foundationCondition: text("foundation_condition"),
    foundationWaterproofing: text("foundation_waterproofing"),
    flooringMaterialPrimary: text("flooring_material_primary"),
    flooringMaterialSecondary: text("flooring_material_secondary"),
    flooringCondition: text("flooring_condition"),
    subfloorMaterial: text("subfloor_material"),
    interiorWallStructureMaterial: text("interior_wall_structure_material"),
    interiorWallStructureMaterialPrimary: text("interior_wall_structure_material_primary"),
    interiorWallStructureMaterialSecondary: text("interior_wall_structure_material_secondary"),
    interiorWallSurfaceMaterialPrimary: text("interior_wall_surface_material_primary"),
    interiorWallSurfaceMaterialSecondary: text("interior_wall_surface_material_secondary"),
    interiorWallFinishPrimary: text("interior_wall_finish_primary"),
    interiorWallFinishSecondary: text("interior_wall_finish_secondary"),
    interiorWallCondition: text("interior_wall_condition"),
    guttersMaterial: text("gutters_material"),
    guttersCondition: text("gutters_condition"),
    ceilingStructureMaterial: text("ceiling_structure_material"),
    ceilingSurfaceMaterial: text("ceiling_surface_material"),
    ceilingInsulationType: text("ceiling_insulation_type"),
    ceilingHeightAverage: numeric("ceiling_height_average", { precision: 8, scale: 2 }),
    ceilingCondition: text("ceiling_condition"),
    exteriorDoorMaterial: text("exterior_door_material"),
    interiorDoorMaterial: text("interior_door_material"),
    windowFrameMaterial: text("window_frame_material"),
    windowGlazingType: text("window_glazing_type"),
    windowOperationType: text("window_operation_type"),
    windowScreenMaterial: text("window_screen_material"),
    primaryFramingMaterial: text("primary_framing_material"),
    secondaryFramingMaterial: text("secondary_framing_material"),
    structuralDamageIndicators: text("structural_damage_indicators"),
    numberOfStories: numeric("number_of_stories", { precision: 8, scale: 2 }),
    finishedBaseArea: integer("finished_base_area"),
    unfinishedBaseArea: integer("unfinished_base_area"),
    finishedBasementArea: integer("finished_basement_area"),
    unfinishedBasementArea: integer("unfinished_basement_area"),
    finishedUpperStoryArea: integer("finished_upper_story_area"),
    unfinishedUpperStoryArea: integer("unfinished_upper_story_area"),
    sourceHttpRequest: nullableJsonObjectColumn("source_http_request"),
    sourcePayload: jsonObjectColumn("source_payload"),
    ...sourceMetadataColumns(),
    createdAt: createdAtColumn(),
    updatedAt: updatedAtColumn(),
  },
  (table) => [
    uniqueIndex("structures_source_record_idx").on(table.sourceSystem, table.sourceRecordKey),
    index("structures_property_idx").on(table.propertyId),
  ],
);

export const floodStormInformation = pgTable(
  "flood_storm_information",
  {
    floodStormInformationId: uuid("flood_storm_information_id").primaryKey().defaultRandom(),
    propertyId: uuid("property_id").references(() => properties.propertyId, {
      onDelete: "cascade",
    }),
    requestIdentifier: text("request_identifier"),
    communityId: text("community_id"),
    panelNumber: text("panel_number"),
    mapVersion: text("map_version"),
    effectiveDate: date("effective_date"),
    evacuationZone: text("evacuation_zone"),
    floodZone: text("flood_zone"),
    floodInsuranceRequired: boolean("flood_insurance_required"),
    femaSearchUrl: text("fema_search_url"),
    sourceHttpRequest: nullableJsonObjectColumn("source_http_request"),
    sourcePayload: jsonObjectColumn("source_payload"),
    ...sourceMetadataColumns(),
    createdAt: createdAtColumn(),
    updatedAt: updatedAtColumn(),
  },
  (table) => [
    uniqueIndex("flood_storm_information_source_record_idx").on(
      table.sourceSystem,
      table.sourceRecordKey,
    ),
    index("flood_storm_information_property_idx").on(table.propertyId),
  ],
);

export const utilities = pgTable(
  "utilities",
  {
    utilityId: uuid("utility_id").primaryKey().defaultRandom(),
    propertyId: uuid("property_id").references(() => properties.propertyId, {
      onDelete: "cascade",
    }),
    layoutId: uuid("layout_id").references(() => layouts.layoutId, {
      onDelete: "set null",
    }),
    requestIdentifier: text("request_identifier"),
    coolingSystemType: text("cooling_system_type"),
    heatingSystemType: text("heating_system_type"),
    heatingFuelType: text("heating_fuel_type"),
    publicUtilityType: text("public_utility_type"),
    sewerType: text("sewer_type"),
    waterSourceType: text("water_source_type"),
    plumbingSystemType: text("plumbing_system_type"),
    plumbingSystemTypeOtherDescription: text("plumbing_system_type_other_description"),
    electricalPanelCapacity: text("electrical_panel_capacity"),
    electricalWiringType: text("electrical_wiring_type"),
    electricalWiringTypeOtherDescription: text("electrical_wiring_type_other_description"),
    hvacCondensingUnitPresent: boolean("hvac_condensing_unit_present"),
    hvacUnitCondition: text("hvac_unit_condition"),
    hvacUnitIssues: text("hvac_unit_issues"),
    hvacCapacityKw: numeric("hvac_capacity_kw", { precision: 12, scale: 4 }),
    hvacCapacityTons: numeric("hvac_capacity_tons", { precision: 12, scale: 4 }),
    hvacSeerRating: numeric("hvac_seer_rating", { precision: 12, scale: 4 }),
    hvacSystemConfiguration: text("hvac_system_configuration"),
    hvacEquipmentComponent: text("hvac_equipment_component"),
    hvacEquipmentManufacturer: text("hvac_equipment_manufacturer"),
    hvacEquipmentModel: text("hvac_equipment_model"),
    hvacInstallationDate: date("hvac_installation_date"),
    solarPanelPresent: boolean("solar_panel_present"),
    solarPanelType: text("solar_panel_type"),
    solarPanelTypeOtherDescription: text("solar_panel_type_other_description"),
    solarInstallationDate: date("solar_installation_date"),
    solarInverterVisible: boolean("solar_inverter_visible"),
    solarInverterManufacturer: text("solar_inverter_manufacturer"),
    solarInverterModel: text("solar_inverter_model"),
    solarInverterInstallationDate: date("solar_inverter_installation_date"),
    smartHomeFeatures: text("smart_home_features"),
    smartHomeFeaturesOtherDescription: text("smart_home_features_other_description"),
    plumbingFixtureCount: integer("plumbing_fixture_count"),
    plumbingFixtureQuality: text("plumbing_fixture_quality"),
    plumbingFixtureTypePrimary: text("plumbing_fixture_type_primary"),
    plumbingSystemInstallationDate: date("plumbing_system_installation_date"),
    electricalPanelInstallationDate: date("electrical_panel_installation_date"),
    electricalRewireDate: date("electrical_rewire_date"),
    sewerConnectionDate: date("sewer_connection_date"),
    waterConnectionDate: date("water_connection_date"),
    waterHeaterManufacturer: text("water_heater_manufacturer"),
    waterHeaterModel: text("water_heater_model"),
    waterHeaterInstallationDate: date("water_heater_installation_date"),
    wellInstallationDate: date("well_installation_date"),
    sourceHttpRequest: nullableJsonObjectColumn("source_http_request"),
    sourcePayload: jsonObjectColumn("source_payload"),
    ...sourceMetadataColumns(),
    createdAt: createdAtColumn(),
    updatedAt: updatedAtColumn(),
  },
  (table) => [
    uniqueIndex("utilities_source_record_idx").on(table.sourceSystem, table.sourceRecordKey),
    index("utilities_property_idx").on(table.propertyId),
    index("utilities_layout_idx").on(table.layoutId),
  ],
);

export const layouts = pgTable(
  "layouts",
  {
    layoutId: uuid("layout_id").primaryKey().defaultRandom(),
    propertyId: uuid("property_id").references(() => properties.propertyId, {
      onDelete: "cascade",
    }),
    parentLayoutId: uuid("parent_layout_id"),
    structureId: uuid("structure_id").references(() => structures.structureId, {
      onDelete: "set null",
    }),
    requestIdentifier: text("request_identifier"),
    spaceType: text("space_type"),
    spaceIndex: integer("space_index"),
    spaceTypeIndex: integer("space_type_index"),
    buildingNumber: text("building_number"),
    storyType: text("story_type"),
    floorLevel: text("floor_level"),
    builtYear: integer("built_year"),
    installationDate: date("installation_date"),
    sizeSquareFeet: numeric("size_square_feet", { precision: 18, scale: 2 }),
    livableAreaSqFt: numeric("livable_area_sq_ft", { precision: 18, scale: 2 }),
    totalAreaSqFt: numeric("total_area_sq_ft", { precision: 18, scale: 2 }),
    heatedAreaSqFt: numeric("heated_area_sq_ft", { precision: 18, scale: 2 }),
    areaUnderAirSqFt: numeric("area_under_air_sq_ft", { precision: 18, scale: 2 }),
    adjustableAreaSqFt: numeric("adjustable_area_sq_ft", { precision: 18, scale: 2 }),
    flooringMaterialType: text("flooring_material_type"),
    flooringInstallationDate: date("flooring_installation_date"),
    hasWindows: boolean("has_windows"),
    windowDesignType: text("window_design_type"),
    windowMaterialType: text("window_material_type"),
    windowTreatmentType: text("window_treatment_type"),
    isFinished: boolean("is_finished"),
    furnished: boolean("furnished"),
    paintCondition: text("paint_condition"),
    flooringWear: text("flooring_wear"),
    clutterLevel: text("clutter_level"),
    visibleDamage: text("visible_damage"),
    countertopMaterial: text("countertop_material"),
    cabinetStyle: text("cabinet_style"),
    fixtureFinishQuality: text("fixture_finish_quality"),
    designStyle: text("design_style"),
    naturalLightQuality: text("natural_light_quality"),
    decorElements: text("decor_elements"),
    kitchenRenovationDate: date("kitchen_renovation_date"),
    bathroomRenovationDate: date("bathroom_renovation_date"),
    poolType: text("pool_type"),
    poolEquipment: text("pool_equipment"),
    poolCondition: text("pool_condition"),
    poolSurfaceType: text("pool_surface_type"),
    poolWaterQuality: text("pool_water_quality"),
    poolInstallationDate: date("pool_installation_date"),
    spaType: text("spa_type"),
    spaInstallationDate: date("spa_installation_date"),
    safetyFeatures: text("safety_features"),
    viewType: text("view_type"),
    lightingFeatures: text("lighting_features"),
    conditionIssues: text("condition_issues"),
    isExterior: boolean("is_exterior"),
    sourceHttpRequest: nullableJsonObjectColumn("source_http_request"),
    sourcePayload: jsonObjectColumn("source_payload"),
    ...sourceMetadataColumns(),
    createdAt: createdAtColumn(),
    updatedAt: updatedAtColumn(),
  },
  (table) => [
    uniqueIndex("layouts_source_record_idx").on(table.sourceSystem, table.sourceRecordKey),
    index("layouts_property_idx").on(table.propertyId),
    index("layouts_parent_idx").on(table.parentLayoutId),
    index("layouts_structure_idx").on(table.structureId),
    foreignKey({
      columns: [table.parentLayoutId],
      foreignColumns: [table.layoutId],
      name: "layouts_parent_layout_fk",
    }).onDelete("set null"),
  ],
);

export const lots = pgTable(
  "lots",
  {
    lotId: uuid("lot_id").primaryKey().defaultRandom(),
    propertyId: uuid("property_id").references(() => properties.propertyId, {
      onDelete: "cascade",
    }),
    requestIdentifier: text("request_identifier"),
    lotType: text("lot_type"),
    lotLengthFeet: numeric("lot_length_feet", { precision: 18, scale: 2 }),
    lotWidthFeet: numeric("lot_width_feet", { precision: 18, scale: 2 }),
    lotAreaSqft: numeric("lot_area_sqft", { precision: 18, scale: 2 }),
    lotSizeAcre: numeric("lot_size_acre", { precision: 18, scale: 6 }),
    landscapingFeatures: text("landscaping_features"),
    view: text("view"),
    fencingType: text("fencing_type"),
    fenceHeight: numeric("fence_height", { precision: 18, scale: 2 }),
    fenceLength: numeric("fence_length", { precision: 18, scale: 2 }),
    drivewayMaterial: text("driveway_material"),
    drivewayCondition: text("driveway_condition"),
    lotConditionIssues: text("lot_condition_issues"),
    pavingAreaSqft: numeric("paving_area_sqft", { precision: 18, scale: 2 }),
    pavingInstallationDate: date("paving_installation_date"),
    pavingType: text("paving_type"),
    siteLightingFixtureCount: integer("site_lighting_fixture_count"),
    siteLightingInstallationDate: date("site_lighting_installation_date"),
    siteLightingType: text("site_lighting_type"),
    sourceHttpRequest: nullableJsonObjectColumn("source_http_request"),
    sourcePayload: jsonObjectColumn("source_payload"),
    ...sourceMetadataColumns(),
    createdAt: createdAtColumn(),
    updatedAt: updatedAtColumn(),
  },
  (table) => [
    uniqueIndex("lots_source_record_idx").on(table.sourceSystem, table.sourceRecordKey),
    index("lots_property_idx").on(table.propertyId),
  ],
);
